// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: proto/cache.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticCache_Get_FullMethodName    = "/cache.SemanticCache/Get"
	SemanticCache_Put_FullMethodName    = "/cache.SemanticCache/Put"
	SemanticCache_Health_FullMethodName = "/cache.SemanticCache/Health"
)

// SemanticCacheClient is the client API for SemanticCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 缓存服务定义
type SemanticCacheClient interface {
	// 查询缓存：返回命中结果或空
	Get(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*CacheResponse, error)
	// 写入缓存：异步调用，不阻塞主请求
	Put(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*Empty, error)
	// 健康检查
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type semanticCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticCacheClient(cc grpc.ClientConnInterface) SemanticCacheClient {
	return &semanticCacheClient{cc}
}

func (c *semanticCacheClient) Get(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*CacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheResponse)
	err := c.cc.Invoke(ctx, SemanticCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheClient) Put(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SemanticCache_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SemanticCache_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticCacheServer is the server API for SemanticCache service.
// All implementations must embed UnimplementedSemanticCacheServer
// for forward compatibility.
//
// 缓存服务定义
type SemanticCacheServer interface {
	// 查询缓存：返回命中结果或空
	Get(context.Context, *CacheRequest) (*CacheResponse, error)
	// 写入缓存：异步调用，不阻塞主请求
	Put(context.Context, *CacheRequest) (*Empty, error)
	// 健康检查
	Health(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedSemanticCacheServer()
}

// UnimplementedSemanticCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticCacheServer struct{}

func (UnimplementedSemanticCacheServer) Get(context.Context, *CacheRequest) (*CacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSemanticCacheServer) Put(context.Context, *CacheRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedSemanticCacheServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSemanticCacheServer) mustEmbedUnimplementedSemanticCacheServer() {}
func (UnimplementedSemanticCacheServer) testEmbeddedByValue()                       {}

// UnsafeSemanticCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticCacheServer will
// result in compilation errors.
type UnsafeSemanticCacheServer interface {
	mustEmbedUnimplementedSemanticCacheServer()
}

func RegisterSemanticCacheServer(s grpc.ServiceRegistrar, srv SemanticCacheServer) {
	// If the following call panics, it indicates UnimplementedSemanticCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticCache_ServiceDesc, srv)
}

func _SemanticCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServer).Get(ctx, req.(*CacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCache_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCache_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServer).Put(ctx, req.(*CacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCache_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCache_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticCache_ServiceDesc is the grpc.ServiceDesc for SemanticCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache.SemanticCache",
	HandlerType: (*SemanticCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SemanticCache_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _SemanticCache_Put_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SemanticCache_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cache.proto",
}
