// This file is @generated by prost-build.
/// 缓存请求：用 embedding 向量 + 元数据作为键
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CacheRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub prompt_text: ::prost::alloc::string::String,
    /// 请求的语义向量（768/1024 维）
    #[prost(float, repeated, tag = "2")]
    pub embedding: ::prost::alloc::vec::Vec<f32>,
    #[prost(string, tag = "3")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub system_prompt_hash: ::prost::alloc::string::String,
    /// embedding 由 Rust 侧内部生成，不通过 gRPC 传输
    #[prost(int64, tag = "5")]
    pub ttl_seconds: i64,
    /// 缓存的完整响应
    #[prost(string, optional, tag = "6")]
    pub response_body: ::core::option::Option<::prost::alloc::string::String>,
    /// 输入 token 数（用于成本统计）
    #[prost(int32, optional, tag = "7")]
    pub input_tokens: ::core::option::Option<i32>,
    /// 输出 token 数
    #[prost(int32, optional, tag = "8")]
    pub output_tokens: ::core::option::Option<i32>,
}
/// 缓存响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CacheResponse {
    /// 是否命中
    #[prost(bool, tag = "1")]
    pub hit: bool,
    /// 命中时返回缓存的完整响应（JSON 字符串）
    #[prost(string, optional, tag = "2")]
    pub response_body: ::core::option::Option<::prost::alloc::string::String>,
    /// 相似度分数（0.0~1.0），用于可观测
    #[prost(float, optional, tag = "3")]
    pub similarity: ::core::option::Option<f32>,
    /// 未命中原因： "miss"/"expired"/"threshold"
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag = "1")]
    pub serving: bool,
}
/// Generated server implementations.
pub mod semantic_cache_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SemanticCacheServer.
    #[async_trait]
    pub trait SemanticCache: std::marker::Send + std::marker::Sync + 'static {
        /// 查询缓存：返回命中结果或空
        async fn get(
            &self,
            request: tonic::Request<super::CacheRequest>,
        ) -> std::result::Result<tonic::Response<super::CacheResponse>, tonic::Status>;
        /// 写入缓存：异步调用，不阻塞主请求
        async fn put(
            &self,
            request: tonic::Request<super::CacheRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        /// 健康检查
        async fn health(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status>;
    }
    /// 缓存服务定义
    #[derive(Debug)]
    pub struct SemanticCacheServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SemanticCacheServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SemanticCacheServer<T>
    where
        T: SemanticCache,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cache.SemanticCache/Get" => {
                    #[allow(non_camel_case_types)]
                    struct GetSvc<T: SemanticCache>(pub Arc<T>);
                    impl<T: SemanticCache> tonic::server::UnaryService<super::CacheRequest> for GetSvc<T> {
                        type Response = super::CacheResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CacheRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as SemanticCache>::get(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cache.SemanticCache/Put" => {
                    #[allow(non_camel_case_types)]
                    struct PutSvc<T: SemanticCache>(pub Arc<T>);
                    impl<T: SemanticCache> tonic::server::UnaryService<super::CacheRequest> for PutSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CacheRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as SemanticCache>::put(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cache.SemanticCache/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: SemanticCache>(pub Arc<T>);
                    impl<T: SemanticCache> tonic::server::UnaryService<super::Empty> for HealthSvc<T> {
                        type Response = super::HealthResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as SemanticCache>::health(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(empty_body());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for SemanticCacheServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cache.SemanticCache";
    impl<T> tonic::server::NamedService for SemanticCacheServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
