// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/cache.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 缓存请求：用 embedding 向量 + 元数据作为键
type CacheRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PromptText       string                 `protobuf:"bytes,9,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	Embedding        []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // 请求的语义向量（768/1024 维）
	Model            string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	SystemPromptHash string                 `protobuf:"bytes,4,opt,name=system_prompt_hash,json=systemPromptHash,proto3" json:"system_prompt_hash,omitempty"`
	TtlSeconds       int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`             // embedding 由 Rust 侧内部生成，不通过 gRPC 传输
	ResponseBody     *string                `protobuf:"bytes,6,opt,name=response_body,json=responseBody,proto3,oneof" json:"response_body,omitempty"`  // 缓存的完整响应
	InputTokens      *int32                 `protobuf:"varint,7,opt,name=input_tokens,json=inputTokens,proto3,oneof" json:"input_tokens,omitempty"`    // 输入 token 数（用于成本统计）
	OutputTokens     *int32                 `protobuf:"varint,8,opt,name=output_tokens,json=outputTokens,proto3,oneof" json:"output_tokens,omitempty"` // 输出 token 数
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CacheRequest) Reset() {
	*x = CacheRequest{}
	mi := &file_proto_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRequest) ProtoMessage() {}

func (x *CacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRequest.ProtoReflect.Descriptor instead.
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CacheRequest) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

func (x *CacheRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *CacheRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CacheRequest) GetSystemPromptHash() string {
	if x != nil {
		return x.SystemPromptHash
	}
	return ""
}

func (x *CacheRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CacheRequest) GetResponseBody() string {
	if x != nil && x.ResponseBody != nil {
		return *x.ResponseBody
	}
	return ""
}

func (x *CacheRequest) GetInputTokens() int32 {
	if x != nil && x.InputTokens != nil {
		return *x.InputTokens
	}
	return 0
}

func (x *CacheRequest) GetOutputTokens() int32 {
	if x != nil && x.OutputTokens != nil {
		return *x.OutputTokens
	}
	return 0
}

// 缓存响应
type CacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hit           bool                   `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`                                            // 是否命中
	ResponseBody  *string                `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3,oneof" json:"response_body,omitempty"` // 命中时返回缓存的完整响应（JSON 字符串）
	Similarity    *float32               `protobuf:"fixed32,3,opt,name=similarity,proto3,oneof" json:"similarity,omitempty"`                       // 相似度分数（0.0~1.0），用于可观测
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                       // 未命中原因： "miss"/"expired"/"threshold"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResponse) Reset() {
	*x = CacheResponse{}
	mi := &file_proto_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResponse) ProtoMessage() {}

func (x *CacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResponse.ProtoReflect.Descriptor instead.
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *CacheResponse) GetResponseBody() string {
	if x != nil && x.ResponseBody != nil {
		return *x.ResponseBody
	}
	return ""
}

func (x *CacheResponse) GetSimilarity() float32 {
	if x != nil && x.Similarity != nil {
		return *x.Similarity
	}
	return 0
}

func (x *CacheResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_cache_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serving       bool                   `protobuf:"varint,1,opt,name=serving,proto3" json:"serving,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_cache_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetServing() bool {
	if x != nil {
		return x.Serving
	}
	return false
}

var File_proto_cache_proto protoreflect.FileDescriptor

const file_proto_cache_proto_rawDesc = "" +
	"\n" +
	"\x11proto/cache.proto\x12\x05cache\"\x82\x03\n" +
	"\fCacheRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vprompt_text\x18\t \x01(\tR\n" +
	"promptText\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12,\n" +
	"\x12system_prompt_hash\x18\x04 \x01(\tR\x10systemPromptHash\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\x12(\n" +
	"\rresponse_body\x18\x06 \x01(\tH\x00R\fresponseBody\x88\x01\x01\x12&\n" +
	"\finput_tokens\x18\a \x01(\x05H\x01R\vinputTokens\x88\x01\x01\x12(\n" +
	"\routput_tokens\x18\b \x01(\x05H\x02R\foutputTokens\x88\x01\x01B\x10\n" +
	"\x0e_response_bodyB\x0f\n" +
	"\r_input_tokensB\x10\n" +
	"\x0e_output_tokens\"\xa9\x01\n" +
	"\rCacheResponse\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x12(\n" +
	"\rresponse_body\x18\x02 \x01(\tH\x00R\fresponseBody\x88\x01\x01\x12#\n" +
	"\n" +
	"similarity\x18\x03 \x01(\x02H\x01R\n" +
	"similarity\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reasonB\x10\n" +
	"\x0e_response_bodyB\r\n" +
	"\v_similarity\"\a\n" +
	"\x05Empty\"*\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aserving\x18\x01 \x01(\bR\aserving2\x9a\x01\n" +
	"\rSemanticCache\x120\n" +
	"\x03Get\x12\x13.cache.CacheRequest\x1a\x14.cache.CacheResponse\x12(\n" +
	"\x03Put\x12\x13.cache.CacheRequest\x1a\f.cache.Empty\x12-\n" +
	"\x06Health\x12\f.cache.Empty\x1a\x15.cache.HealthResponseB<Z:github.com/skylunna/tiny-agent-router/internal/cache/protob\x06proto3"

var (
	file_proto_cache_proto_rawDescOnce sync.Once
	file_proto_cache_proto_rawDescData []byte
)

func file_proto_cache_proto_rawDescGZIP() []byte {
	file_proto_cache_proto_rawDescOnce.Do(func() {
		file_proto_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cache_proto_rawDesc), len(file_proto_cache_proto_rawDesc)))
	})
	return file_proto_cache_proto_rawDescData
}

var file_proto_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_cache_proto_goTypes = []any{
	(*CacheRequest)(nil),   // 0: cache.CacheRequest
	(*CacheResponse)(nil),  // 1: cache.CacheResponse
	(*Empty)(nil),          // 2: cache.Empty
	(*HealthResponse)(nil), // 3: cache.HealthResponse
}
var file_proto_cache_proto_depIdxs = []int32{
	0, // 0: cache.SemanticCache.Get:input_type -> cache.CacheRequest
	0, // 1: cache.SemanticCache.Put:input_type -> cache.CacheRequest
	2, // 2: cache.SemanticCache.Health:input_type -> cache.Empty
	1, // 3: cache.SemanticCache.Get:output_type -> cache.CacheResponse
	2, // 4: cache.SemanticCache.Put:output_type -> cache.Empty
	3, // 5: cache.SemanticCache.Health:output_type -> cache.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cache_proto_init() }
func file_proto_cache_proto_init() {
	if File_proto_cache_proto != nil {
		return
	}
	file_proto_cache_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_cache_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cache_proto_rawDesc), len(file_proto_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cache_proto_goTypes,
		DependencyIndexes: file_proto_cache_proto_depIdxs,
		MessageInfos:      file_proto_cache_proto_msgTypes,
	}.Build()
	File_proto_cache_proto = out.File
	file_proto_cache_proto_goTypes = nil
	file_proto_cache_proto_depIdxs = nil
}
